[package]
name = "osdev"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "osdev"
test = false
bench = false

[dependencies]
bootloader = "0.9"
