[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-osdev.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
